// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxybzrcwmriwsmetrbqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4eWJ6cmN3bXJpd3NtZXRyYnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNzQ4NTksImV4cCI6MjA1MTc1MDg1OX0.jMuOR9DYFD_8d5xwEOGqtFBI7DsbLnmmTE2qMhIugeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);